language: php
php:
  - 7.0
  - 5.6

install:
  - composer self-update
  - composer install


script:  
  - ./vendor/bin/phpunit --whitelist ./tests --coverage-clover ./coverage.xml --colors=always
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml